{
 "title": "Credential Manager",
 "description": "Dashboard for Credential Manager monitor Metrics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "namespace", "query": "releaseNamespace" }
  ]
 },
 "panels": [
  { "title": "I/O Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Rate",
   "type": "graph",
   "description": "The number of requests, per second, the service is serving.",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "description": "The number of failed requests per second.",
   "gridPos": { "h": 7, "w": 8, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_error_total{namespace=\"$namespace\"}[$__rate_interval])) by (status)",
     "legendFormat": "HTTP {{status}}"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "description": "The amount of time each request takes expressed as a time interval.",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_seconds_sum{namespace=\"$namespace\"}[$__rate_interval]))/sum(rate(http_requests_seconds_count{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "HTTP - AVG"
    }
   ]
  },
  { "title": "Memory/CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Process Memory",
   "type": "graph",
   "description": "Virtual memory: It is the amount of address space that a process is managing. This includes all types of memory, both in RAM and swapped out.\nResident memory: It is the number of memory pages the process has in real memory, with pagesize. This results in the amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{namespace=\"$namespace\", job=\"credential-manager\"}",
     "legendFormat": "virtual"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", job=\"credential-manager\"}",
     "legendFormat": "resident"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "description": "System CPU usage is host's cumulative CPU usage. This includes user, system, idle CPU modes.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total{namespace=\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "process"
    }
   ]
  }
 ]
}